version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_123
      MYSQL_DATABASE: bookstore
    ports:
      - '3306:3306'
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data: